# Generated by Django 4.2.2 on 2023-08-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
