# Generated by Django 4.2.2 on 2023-08-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
