# Generated by Django 4.2.2 on 2023-08-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_signup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='last_login',
        ),
    ]
