# Generated by Django 4.2.2 on 2023-08-21 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0006_remove_signup_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='sex',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
