# Generated by Django 4.2.2 on 2023-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_signup_contact_signup_dob_signup_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
