# Generated by Django 4.2.2 on 2023-08-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_signup_first_name_signup_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
    ]
