# Generated by Django 4.2.2 on 2023-09-03 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0013_customeruser_remove_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
