# Generated by Django 4.2.2 on 2023-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_customeruser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
