# Generated by Django 4.2.2 on 2023-09-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_customeruser_username_alter_staff_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='contact',
        ),
    ]
