# Generated by Django 4.2.2 on 2023-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_alter_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, choices=[('Khan Boeng Keng Kang', 'Khan Boeng Keng Kang'), ('Doun Penh section', 'Doun Penh section'), ('Khan Kamboul', 'Khan Kamboul'), ('Khan Chamkar Mon', 'Khan Chamkar Mon'), ('Khan Chbar Ampov', 'Khan Chbar Ampov'), ('Khan Chroy Changvar', 'Khan Chroy Changvar'), ('Khan Dangkao', 'Khan Dangkao'), ('Khan Mean Chey', 'Khan Mean Chey'), ('Khan Pou Senchey', 'Khan Pou Senchey'), ('Khan Prampir Makara', 'Khan Prampir Makara'), ('Khan Russey Keo', 'Khan Russey Keo'), ('Khan Sen Sok', 'Khan Sen Sok'), ('Khan Tuol Kouk', 'Khan Tuol Kouk'), ('Khan Prek Pnov', 'Khan Prek Pnov')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='road',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
