# Generated by Django 4.2.2 on 2023-09-14 16:20

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=userprofile.models.user_directory_path, validators=[userprofile.models.validate_file_extension]),
        ),
    ]
