# Generated by Django 4.2.2 on 2023-08-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Soda', 'Soda'), ('Milk', 'Milk')], max_length=100, null=True),
        ),
    ]
