# Generated by Django 4.2.2 on 2023-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_size_name_size_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=50, null=True),
        ),
    ]
