# Generated by Django 4.2.2 on 2023-09-02 10:55

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_size_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, upload_to=menu.models.menu_directory_path, validators=[menu.models.validate_file_extension])),
                ('category', models.CharField(blank=True, choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Soda', 'Soda'), ('Milk', 'Milk')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sizes', models.ManyToManyField(blank=True, null=True, to='menu.size')),
            ],
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.addproduct'),
        ),
    ]
