# Generated by Django 4.2.2 on 2023-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_orderitem_checkout_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='checkouts', to='menu.orderitem'),
        ),
    ]
