# Generated by Django 4.2.2 on 2023-09-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_addproduct_remove_productprice_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='menu.size'),
        ),
    ]
