# Generated by Django 4.2.2 on 2023-09-14 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_checkout_orderitem_checkout_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
