# Generated by Django 4.2.2 on 2023-09-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_checkout_checkout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
