# Generated by Django 4.2.2 on 2023-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_checkout_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
