# Generated by Django 4.2.2 on 2023-09-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=50, null=True),
        ),
    ]
