# Generated by Django 4.2.2 on 2023-09-08 04:00

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_size_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=menu.models.menu_directory_path, validators=[menu.models.validate_file_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='image',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='images',
            field=models.ManyToManyField(blank=True, to='menu.image'),
        ),
    ]
