# Generated by Django 4.2.2 on 2023-09-08 04:24

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_image_remove_addproduct_image_alter_addproduct_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=menu.models.menu_directory_path, validators=[menu.models.validate_file_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='images',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.addproduct'),
        ),
    ]
