# Generated by Django 4.2.2 on 2023-09-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_productimage_remove_addproduct_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='sizes',
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='menu.addproduct')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.size')),
            ],
        ),
    ]
