# Generated by Django 4.2.2 on 2023-09-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_addproduct_price_remove_addproduct_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='menu.size'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
