# Generated by Django 4.2.2 on 2023-09-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_addproduct_price_addproduct_sizes_delete_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
