# Generated by Django 4.2.2 on 2023-09-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_size_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
    ]
