# Generated by Django 4.2.2 on 2023-09-09 01:10

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_size_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('images', models.FileField(blank=True, upload_to=menu.models.menu_directory_path, validators=[menu.models.validate_file_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='menu.addproduct'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.size'),
        ),
    ]
