# Generated by Django 4.2.2 on 2023-09-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_productsize_remove_addproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
