# Generated by Django 4.2.2 on 2023-09-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_orderdetail_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.productsize'),
        ),
    ]
