# Generated by Django 4.2.2 on 2023-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_orderdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
