# Generated by Django 4.2.2 on 2023-09-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
