# Generated by Django 4.2.2 on 2023-09-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_remove_customeruser_contact'),
        ('menu', '0023_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.customer')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orderdetail')),
            ],
        ),
    ]
