# Generated by Django 4.2.2 on 2023-09-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='road',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
