# Generated by Django 4.2.2 on 2023-09-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_checkout_district_checkout_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_details',
            field=models.ManyToManyField(to='menu.orderdetail'),
        ),
    ]
