# Generated by Django 4.2.2 on 2023-09-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_remove_checkout_order_detail_checkout_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='location',
        ),
    ]
