# Generated by Django 4.2.2 on 2023-09-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_remove_customer_location_customer_district_and_more'),
        ('menu', '0027_remove_checkout_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='district',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='road',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.customer'),
        ),
    ]
