# Generated by Django 4.2.2 on 2023-09-13 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_completedorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedorder',
            options={},
        ),
        migrations.AddField(
            model_name='checkout',
            name='completed_orders',
            field=models.ManyToManyField(blank=True, to='menu.completedorder'),
        ),
        migrations.AlterField(
            model_name='completedorder',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
