# Generated by Django 4.2.2 on 2023-09-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_alter_completedorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_details',
        ),
    ]
