# Generated by Django 4.2.2 on 2023-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_checkout_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='completed_orders',
        ),
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
    ]
