# Generated by Django 4.2.2 on 2023-09-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_remove_checkout_completed_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.checkout')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orderdetail')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productsize')),
            ],
        ),
    ]
