# Generated by Django 4.2.2 on 2023-09-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
    ]
