# Generated by Django 4.2.2 on 2023-09-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_remove_order_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout',
        ),
    ]
