# Generated by Django 4.2.2 on 2023-09-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_checkout_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
