# Generated by Django 4.2.2 on 2023-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ManyToManyField(to='menu.order'),
        ),
    ]
