# Generated by Django 4.2.2 on 2023-09-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_checkout_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orderdetail'),
        ),
    ]
