# Generated by Django 4.2.2 on 2023-09-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0043_remove_order_product_size_alter_order_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.orderdetail'),
        ),
    ]
