# Generated by Django 4.2.2 on 2023-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0044_remove_order_quantity_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_sizes',
            field=models.ManyToManyField(to='menu.productsize'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
