# Generated by Django 4.2.2 on 2023-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0046_remove_orderdetail_product_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_sizes',
            field=models.ManyToManyField(to='menu.productsize'),
        ),
    ]
