# Generated by Django 4.2.2 on 2023-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0047_remove_orderdetail_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_sizes',
            field=models.ManyToManyField(blank=True, to='menu.productsize'),
        ),
    ]
