# Generated by Django 4.2.2 on 2023-09-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0048_alter_orderdetail_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_sizes',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_sizes',
            field=models.ManyToManyField(to='menu.productsize', verbose_name='Product Sizes'),
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orderdetail')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productsize')),
            ],
        ),
    ]
