# Generated by Django 4.2.2 on 2023-09-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0049_remove_orderdetail_product_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product_sizes',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.productsize'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
