# Generated by Django 4.2.2 on 2023-09-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0050_remove_checkout_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orderdetail')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ManyToManyField(to='menu.order'),
        ),
    ]
