# Generated by Django 4.2.2 on 2023-09-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0051_alter_orderdetail_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
