# Generated by Django 4.2.2 on 2023-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0053_alter_orderdetail_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
