# Generated by Django 4.2.2 on 2023-09-14 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_alter_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0056_alter_checkout_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('confirm_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.customer')),
                ('order_details', models.ManyToManyField(to='menu.orderdetail')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
