# Generated by Django 4.2.2 on 2023-09-14 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0058_confirm_product_size_alter_confirm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='confirm',
            name='order_details',
        ),
        migrations.AddField(
            model_name='checkout',
            name='confirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.confirm'),
        ),
    ]
