# Generated by Django 4.2.2 on 2023-09-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0059_remove_checkout_order_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='quantity',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
