# Generated by Django 4.2.2 on 2023-09-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0060_confirm_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='order_details',
            field=models.ManyToManyField(to='menu.orderdetail'),
        ),
    ]
