# Generated by Django 4.2.2 on 2023-09-14 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0061_confirm_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='confirm',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='confirm',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('confirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.confirm')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productsize')),
            ],
        ),
    ]
