# Generated by Django 4.2.2 on 2023-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0062_remove_confirm_order_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='confirm',
        ),
        migrations.AddField(
            model_name='confirm',
            name='order_items',
            field=models.ManyToManyField(to='menu.orderitem'),
        ),
    ]
