# Generated by Django 4.2.2 on 2023-09-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0065_confirm_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='order_details',
        ),
    ]
