# Generated by Django 4.2.2 on 2023-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0066_remove_confirm_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='confirm',
            name='order_details',
            field=models.ManyToManyField(to='menu.orderdetail'),
        ),
    ]
