# Generated by Django 4.2.2 on 2023-09-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0067_remove_confirm_orderitem_confirm_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='order_details',
        ),
        migrations.AddField(
            model_name='confirm',
            name='products',
            field=models.ManyToManyField(blank=True, to='menu.productsize'),
        ),
        migrations.AddField(
            model_name='confirm',
            name='quantity',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
