# Generated by Django 4.2.2 on 2023-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0068_remove_confirm_order_details_confirm_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
