# Generated by Django 4.2.2 on 2023-09-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0069_confirm_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='total_price',
        ),
    ]
