# Generated by Django 4.2.2 on 2023-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0071_remove_confirm_quantity_productquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='quantity',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='confirm',
            name='products',
            field=models.ManyToManyField(blank=True, to='menu.productsize'),
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
    ]
