# Generated by Django 4.2.2 on 2023-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0073_remove_confirm_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='quantity',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
