# Generated by Django 4.2.2 on 2023-09-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0074_confirm_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='quantity',
        ),
    ]
