# Generated by Django 4.2.2 on 2023-09-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0075_remove_confirm_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='products',
        ),
        migrations.AddField(
            model_name='confirm',
            name='order_details',
            field=models.ManyToManyField(to='menu.orderdetail'),
        ),
    ]
