# Generated by Django 4.2.2 on 2023-09-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0077_remove_confirm_order_details_confirm_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('confirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.confirm')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productsize')),
            ],
        ),
        migrations.AlterField(
            model_name='confirm',
            name='products',
            field=models.ManyToManyField(blank=True, through='menu.ConfirmedProduct', to='menu.productsize'),
        ),
    ]
