# Generated by Django 4.2.2 on 2023-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0078_confirmedproduct_alter_confirm_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='products',
            field=models.ManyToManyField(blank=True, to='menu.productsize'),
        ),
        migrations.DeleteModel(
            name='ConfirmedProduct',
        ),
    ]
