# Generated by Django 4.2.2 on 2023-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0079_alter_confirm_products_delete_confirmedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='products',
        ),
        migrations.AddField(
            model_name='confirm',
            name='order_items',
            field=models.ManyToManyField(related_name='confirmations', to='menu.orderitem'),
        ),
    ]
