# Generated by Django 4.2.2 on 2023-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0080_remove_confirm_products_confirm_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='order_items',
        ),
        migrations.AddField(
            model_name='confirm',
            name='products',
            field=models.ManyToManyField(blank=True, to='menu.productsize'),
        ),
    ]
